config/routes.rb
Rails.application.routes.draw do
  get 'pages/viewtype', as: 'page', alias: 'p'

  resources :menu_items
  resources :menus do
    collection { post 'import' }
  end

  resources :menu_pages do
    collection { post 'import' }
  end

  resources :dishes do
    collection { post 'import' }
  end

  resources :menu_items do
    collection { post 'import' }
  end

  root to: 'menus#index'
end

app/models/menu_item.rb
# == Schema Information
#
# Table name: menu_items
#
#  id           :integer          not null, primary key
#  menu_page_id :integer
#  price        :float
#  high_price   :float
#  dish_id      :integer
#  xpos         :decimal(, )      not null
#  ypos         :decimal(, )      not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class MenuItem < ApplicationRecord
  belongs_to :menu_page
  belongs_to :dish
  has_one :menu, through: :menu_page

  validates_presence_of :xpos, :ypos
  validates_associated :menu_page
  validates_associated :dish

  def self.bulk_import(file)
    CsvImportService.new(self, file).process
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_menu_item, only: %i[show edit update destroy]

  # GET /menu_items
  # GET /menu_items.json
  def index
    @menu_items = MenuItem.includes(%i[dish menu_page]).all.page params[:page]
  end

  # GET /menu_items/1
  # GET /menu_items/1.json
  def show; end

  # GET /menu_items/new
  def new
    @menu_item = MenuItem.new
  end

  # GET /menu_items/1/edit
  def edit; end

  # POST /menu_items
  # POST /menu_items.json
  def create
    @menu_item = MenuItem.new(menu_item_params)

    respond_to do |format|
      if @menu_item.save
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully created.' }
        format.json { render :show, status: :created, location: @menu_item }
      else
        format.html { render :new }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_items/1
  # PATCH/PUT /menu_items/1.json
  def update
    respond_to do |format|
      if @menu_item.update(menu_item_params)
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu_item }
      else
        format.html { render :edit }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items/1
  # DELETE /menu_items/1.json
  def destroy
    @menu_item.destroy
    respond_to do |format|
      format.html { redirect_to menu_items_url, notice: 'Menu item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    MenuItem.bulk_import(params[:csv_file])
    flash[:success] = 'Menu Items imported'
    redirect_to menu_pages_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_menu_item
    @menu_item = MenuItem.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def menu_item_params
    params.require(:menu_item).permit(:menu_page_id, :price, :high_price, :dish_id, :xpos, :ypos)
  end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/menu_items/_form.html.erb
<%= simple_form_for(@menu_item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :menu_page %>
    <%= f.input :price %>
    <%= f.input :high_price %>
    <%= f.association :dish %>
    <%= f.input :xpos %>
    <%= f.input :ypos %>
  </div>

  <div class="form-actions">
    <%= f.button :submit,  class: "btn btn-primary" %>
  </div>
<% end %>

app/views/menu_items/_menu_item.html.erb
<div class="card card-block">
  <div class="card-header bg-success text-white">
    <%= menu_item.dish.name %>
    <small> (Dish id: <%= link_to menu_item.dish.id, menu_item.dish  %>)</small>
  </div>
  <div class="card-body">Description: <%= menu_item.dish.description || 'NA' %></div> 
  <div class="card-footer bg-dark text-white">
    Price: <%= menu_item.price || 'NA' %>
  </div>
</div>

app/views/menu_items/edit.html.erb
<h1>Editing Menu Item</h1>

<%= render 'form', menu_item: @menu_item %>

<%= link_to 'Show', @menu_item %> |
<%= link_to 'Back', menu_items_path %> | 
<%= link_to 'Destroy', @menu_item, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/menu_items/index.html.erb
<div class="float-right">
  <%= link_to 'New Menu Item', new_menu_item_path, class: "btn btn-success" %>
</div>

<h1>Menu Items</h1>

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>ID</th>
      <th>Menu page</th>
      <th>Dish</th>
      <th>Price</th>
      <th></th>
    </tr>
  </thead> 
  <% count = 1 %>
  <tbody>
    <% @menu_items.each do |menu_item| %>
      <tr>
        <td><%= count + params[:page].to_i * 100 %></td>
        <td><%= menu_item.id %></td>
        <td><%= link_to "Menu", menu_item.menu_page %></td>
        <td><%= link_to "Dish", menu_item.dish %></td>
        <td><%= menu_item.price %></td>
        <td><%= link_to 'Show', menu_item %></td>
      </tr>
      <% count += 1 %>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @menu_items %>

app/views/menu_items/new.html.erb
<%= render 'layouts/import_csv_form', object: @menu_item %>

<hr>

<%= link_to 'Back', menu_items_path %>

app/views/menu_items/show.html.erb
<%= render @menu_item %>

<hr>

<h4>Details</h4>

<strong>Menu page:</strong>
<%= link_to @menu_item.menu_page.id, @menu_item.menu_page %>, 

<strong>Price:</strong>
<%= @menu_item.price %>, 

<strong>High price:</strong>
<%= @menu_item.high_price %>, 

<strong>Dish:</strong>
<%= link_to @menu_item.dish.id, @menu_item.dish %>, 

<strong>Xpos:</strong>
<%= @menu_item.xpos %>, 

<strong>Ypos:</strong>
<%= @menu_item.ypos %>, 

<hr>

<%= link_to 'Edit', edit_menu_item_path(@menu_item) %>