config/routes.rb
Rails.application.routes.draw do
  get 'pages/viewtype', as: 'page', alias: 'p'

  resources :menu_items
  resources :menus do
    collection { post 'import' }
  end

  resources :menu_pages do
    collection { post 'import' }
  end

  resources :dishes do
    collection { post 'import' }
  end

  resources :menu_items do
    collection { post 'import' }
  end

  root to: 'menus#index'
end

app/models/dish.rb
# Contains Dish class
# == Schema Information
#
# Table name: dishes
#
#  id             :integer          not null, primary key
#  name           :string
#  description    :string
#  first_appeared :integer
#  last_appeared  :integer
#  lowest_price   :float
#  highest_price  :float
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  menus_appeared :integer
#  times_appeared :integer
#

class Dish < ApplicationRecord
  validates :name, presence: true

  has_many :menu_items, inverse_of: :Dish

  def self.bulk_import(file)
    CsvImportService.new(self, file).process
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: %i[show edit update destroy]

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all.page params[:page]
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show; end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit; end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Dish.bulk_import(params[:csv_file])
    flash[:success] = 'Dishes imported'
    redirect_to dishes_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_dish
    @dish = Dish.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dish_params
    params.require(:dish).permit(:name, :description, :first_appeared, :last_appeared, :lowest_price, :highest_price)
  end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_form.html.erb
<%= simple_form_for(dish, local: true) do |form| %>
<% if dish.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

  <ul>
    <% dish.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<%= form.input :name %>
<%= form.input :description %>
<%= form.input :first_appeared %>
<%= form.input :last_appeared %>
<%= form.input :lowest_price %>
<%= form.input :highest_price %>


<%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form', dish: @dish %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %> |
<%= link_to 'Destroy', @dish , method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/dishes/index.html.erb
<div class="float-right">
  <%= link_to 'New Dish', new_dish_path, class: 'btn btn-success' %>
</div>

<h1>Dishes</h1>

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Description</th>
      <th>First appeared</th>
      <th>Last appeared</th>
      <th>Lowest price</th>
      <th>Highest price</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% count = 1 %>
    <% @dishes.each do |dish| %>
      <tr>
        <td><%= count + params[:page].to_i * 100 %></td>
        <td><%= dish.name %></td>
        <td><%= dish.description %></td>
        <td><%= dish.first_appeared %></td>
        <td><%= dish.last_appeared %></td>
        <td><%= dish.lowest_price %></td>
        <td><%= dish.highest_price %></td>
        <td><%= link_to 'Show', dish %></td>
      </tr>
      <% count += 1 %>
    <% end %>
  </tbody>
</table>

<div class='text-center'>
  <%= paginate @dishes%>
</div>

<br>

app/views/dishes/new.html.erb
<%= render 'layouts/import_csv_form', object: @dish %>

<hr>


<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @dish.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @dish.description %>
</p>

<p>
  <strong>First appeared:</strong>
  <%= @dish.first_appeared %>
</p>

<p>
  <strong>Last appeared:</strong>
  <%= @dish.last_appeared %>
</p>

<p>
  <strong>Lowest price:</strong>
  <%= @dish.lowest_price %>
</p>

<p>
  <strong>Highest price:</strong>
  <%= @dish.highest_price %>
</p>

<%= link_to 'Edit', edit_dish_path(@dish) %>