config/routes.rb
Rails.application.routes.draw do
  get 'pages/viewtype', as: 'page', alias: 'p'

  resources :menu_items
  resources :menus do
    collection { post 'import' }
  end

  resources :menu_pages do
    collection { post 'import' }
  end

  resources :dishes do
    collection { post 'import' }
  end

  resources :menu_items do
    collection { post 'import' }
  end

  root to: 'menus#index'
end

app/models/menu_page.rb
# == Schema Information
#
# Table name: menu_pages
#
#  id          :integer          not null, primary key
#  menu_id     :integer          not null
#  page_number :integer
#  image_id    :integer          not null
#  full_height :integer
#  full_width  :integer
#  uuid        :string           not null
#

class MenuPage < ApplicationRecord
  belongs_to :menu
  has_many :menu_items, inverse_of: :menu_page

  validates :menu_id, uniqueness: { scope: :page_number,
                                    message: 'Duplicate entry for menu/page number combination' }

  validates_presence_of :menu_id, :image_id, :uuid

  # uuid is assumed to not be unique as the data provided has many duplicates

  def self.bulk_import(file)
    CsvImportService.new(self, file).process
  end
end

app/controllers/menu_pages_controller.rb
class MenuPagesController < ApplicationController
  before_action :set_menu_page, only: %i[edit update destroy]

  # GET /menu_pages
  # GET /menu_pages.json
  def index
    @menu_pages = MenuPage.includes(:menu).all.page params[:page]
  end

  # GET /menu_pages/1
  # GET /menu_pages/1.json
  def show
    @menu_page = MenuPage.includes(menu_items: :dish).find(params[:id])
  end

  # GET /menu_pages/new
  def new
    @menu_page = MenuPage.new
  end

  # GET /menu_pages/1/edit
  def edit; end

  # POST /menu_pages
  # POST /menu_pages.json
  def create
    @menu_page = MenuPage.new(menu_page_params)

    respond_to do |format|
      if @menu_page.save
        format.html { redirect_to @menu_page, notice: 'Menu page was successfully created.' }
        format.json { render :show, status: :created, location: @menu_page }
      else
        format.html { render :new }
        format.json { render json: @menu_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_pages/1
  # PATCH/PUT /menu_pages/1.json
  def update
    respond_to do |format|
      if @menu_page.update(menu_page_params)
        format.html { redirect_to @menu_page, notice: 'Menu page was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu_page }
      else
        format.html { render :edit }
        format.json { render json: @menu_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_pages/1
  # DELETE /menu_pages/1.json
  def destroy
    @menu_page.destroy
    respond_to do |format|
      format.html { redirect_to menu_pages_url, notice: 'Menu page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    MenuPage.bulk_import(params[:csv_file])
    flash[:success] = 'Menu Pages imported'
    redirect_to menu_pages_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_menu_page
    @menu_page = MenuPage.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def menu_page_params
    params.require(:menu).permit(:menu_id, :page_number, :image_id, :full_height, :full_width, :uuid)
  end
end

app/helpers/menu_pages_helper.rb
module MenuPagesHelper
end

app/views/menu_pages/_form.html.erb
<%= simple_form_for(@menu_page) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :menu %>
    <%= f.input :page_number %>
    <%= f.input :image_id %>
    <%= f.input :full_width %>
    <%= f.input :full_height %>
    <%= f.input :uuid %>
  </div>

  <div class="form-actions">
    <%= f.button :submit,  class: "btn btn-primary" %>
  </div>
<% end %>

app/views/menu_pages/_menu_page.html.erb
<div class="card card-block">
  <div class="card-header">Page # <%= menu_page.page_number %></div>
  <div class="card-body">
    <% if menu_page.menu_items.any? %>
      <div class="row">
        <% menu_page.menu_items.each do |menu_item| %>
          <div class="col-xs-12 col-sm-6 col-md-4">
            <%= render menu_item %>
            <hr>
          </div>
        <% end %>
      </div>
    <% end %>
  </div> 
  <div class="card-footer"><%= link_to 'View Page', menu_page %></div>
</div>

app/views/menu_pages/edit.html.erb
<h1>Editing Menu Page</h1>

<%= render 'form', menu_page: @menu_page %>

<%= link_to 'Show', @menu_page %> |
<%= link_to 'Back', menu_pages_path %> | 
<%= link_to 'Destroy', @menu_page, method: :delete,
                 data: { confirm: 'Are you sure?' } %>

app/views/menu_pages/index.html.erb
<div class="float-right">
  <%= link_to 'New Menu Page', new_menu_page_path, class: "btn btn-success" %>
</div>

<h1>Menu Pages</h1>

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>ID</th>
      <th>Menu</th>
      <th></th>

    </tr>
  </thead>

  <% count = 1 %>

  <tbody>
    <% @menu_pages.each do |menu_page| %>
      <tr>
        <td><%= count + params[:page].to_i * 100 %></td>
        <td><%= menu_page.id %></td>
        <td><%=  link_to menu_page.menu.id, menu_page.menu %></td>
        <td><%= link_to 'Show', menu_page %></td>
      </tr>
      <% count += 1 %>
    <% end %>
  </tbody>
</table>

<%= paginate @menu_pages %>

app/views/menu_pages/new.html.erb
<%= render 'layouts/import_csv_form', object: @menu_page %>

<hr>

<%= link_to 'Back', menu_pages_path %>

app/views/menu_pages/show.html.erb
<%= render  @menu_page  %>

<hr>
<h4>Details</h4>

<strong>ID</strong>: <%= @menu_page.id %>,
<strong>Menu</strong>: <%= link_to 'Menu', @menu_page.menu %>,
<strong>Page Number</strong>: <%= @menu_page.page_number %>,
<strong>Image ID</strong>: <%= @menu_page.image_id %>,
<strong>Full h</strong>: <%= @menu_page.full_height %>,
<strong>Full W</strong>:<%= @menu_page.full_width %>,
<strong>UUID</strong>: <%= @menu_page.uuid %>

<hr>

<%= link_to 'Edit', edit_menu_page_path(@menu_page) %>