config/routes.rb
Rails.application.routes.draw do
  get 'pages/viewtype', as: 'page', alias: 'p'

  resources :menu_items
  resources :menus do
    collection { post 'import' }
  end

  resources :menu_pages do
    collection { post 'import' }
  end

  resources :dishes do
    collection { post 'import' }
  end

  resources :menu_items do
    collection { post 'import' }
  end

  root to: 'menus#index'
end

app/views/layouts/_import_csv_form.html.erb
<div class="card card-block">
  <h3>Import <%= object.class.name.pluralize.titleize %> </h3>
  <%= form_with url: "/#{object.class.name.underscore.pluralize}/import", multipart: true do |f| %>
    <div class="form-group">
      <%= f.label "Select CSV file" %><br>
      <%= f.file_field :csv_file, label: "Select CSV file" %>
    </div>
    <div class="form control">
      <%= f.submit "Import CSV", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message| %>
<div class="alert alert-<%= message_type %> alert-dismissible fade show" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <%= message.html_safe %>
</div>
<% end %>

app/views/layouts/_topnav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Data App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
        <%= link_to 'Menus', menus_path, class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to "Events", page_path(type: 'event'), class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to "Places", page_path(type: 'place'), class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to "Venues", page_path(type: 'venue'), class: 'nav-link' %>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Other Items
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          
          <%= link_to 'Menu Pages', menu_pages_path, class: "dropdown-item" %>
          <%= link_to 'Menu Items', menu_items_path, class: "dropdown-item" %>
          <%= link_to 'Dishes', dishes_path, class: "dropdown-item" %>
        </div>
      </li>
      
    </ul>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hivetec</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/topnav' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>